name: gshopp_flutter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3
  flutter_native_splash: ^2.3.6
  smooth_page_indicator: ^1.1.0
  go_router: ^13.2.0
  google_nav_bar: ^5.0.6
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  change_app_package_name: ^1.1.0
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.16.0
  firebase_storage: ^11.7.0
  connectivity_plus: ^5.0.2
  animated_snack_bar: ^0.4.0
  get: ^4.6.6
  lottie: ^3.0.0
  vector_math: ^2.1.4
  iconsax: ^0.0.8
  file_picker: ^8.0.0+1
  cached_network_image: ^3.3.0
  image_picker: ^1.0.5
  intl: ^0.19.0
  dotted_line: ^3.2.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  simple_animations: ^5.0.2
  supercharged: ^2.1.1
  modal_bottom_sheet: ^3.0.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.7


flutter:

  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/promo/
    - assets/images/products/
    - assets/images/authentication/
    - assets/logos/
    - assets/storyset/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/icons/ui/
  fonts:
    - family: Freight
      fonts:
        - asset: assets/fonts/freight/Freight-Semibold.otf
          weight: 600
        - asset: assets/fonts/freight/Freight-Bold.otf
          weight: 700
        - asset: assets/fonts/freight/Freight-Black.otf
          weight: 900
        - asset: assets/fonts/freight/Freight-Medium.otf
          weight: 300
        - asset: assets/fonts/freight/Freight-Bold-Italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/freight/Freight-Semibold-Italic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/freight/Freight-Medium-Italic.otf
          weight: 300
          style: italic

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
          weight: 100
          style: italic
  
